<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>MoreBotsPlugin</AssemblyName>
    <Description>API for adding custom bot types.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
	<Configurations>Debug;Release</Configurations>
	<RootNamespace>MoreBotsAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prepatch\Prepatch.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
		  <HintPath>D:\SPT\BepInEx\core\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="DrakiaXYZ-BigBrain">
		  <HintPath>D:\SPT\BepInEx\plugins\DrakiaXYZ-BigBrain.dll</HintPath>
		</Reference>
		<Reference Include="SAIN">
		  <HintPath>D:\SPT\BepInEx\plugins\SAIN\SAIN.dll</HintPath>
		</Reference>
		<Reference Include="spt-custom">
		  <HintPath>D:\SPT\BepInEx\plugins\spt\spt-custom.dll</HintPath>
		</Reference>
		<Reference Include="spt-singleplayer">
		  <HintPath>D:\SPT\BepInEx\plugins\spt\spt-singleplayer.dll</HintPath>
		</Reference>
		<Reference Include="spt-common">
		  <HintPath>D:\SPT\BepInEx\plugins\spt\spt-common.dll</HintPath>
		</Reference>
		<Reference Include="spt-reflection">
		  <HintPath>D:\SPT\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
		</Reference>
		<Reference Include="AnimationSystem.Types">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\AnimationSystem.Types.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
		  <HintPath>D:\SPT\BepInEx\core\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="bsg.console.core">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\bsg.console.core.dll</HintPath>
		</Reference>
		<Reference Include="Comfort">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
		</Reference>
		<Reference Include="Comfort.Unity">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Comfort.Unity.dll</HintPath>
		</Reference>
		<Reference Include="DissonanceVoip">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\DissonanceVoip.dll</HintPath>
		</Reference>
		<Reference Include="ItemComponent.Types">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\ItemComponent.Types.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Sirenix.Serialization">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Postprocessing.Runtime">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Unity.Postprocessing.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
		  <HintPath>D:\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="if not exist &quot;D:\SPT\BepInEx\plugins\MoreBotsAPI&quot; mkdir &quot;D:\SPT\BepInEx\plugins\MoreBotsAPI&quot;&#xA;copy /Y &quot;$(TargetPath)&quot; &quot;D:\SPT\BepInEx\plugins\MoreBotsAPI\$(TargetFileName)&quot;" />
	</Target>

</Project>